<script setup>
defineProps({ modelValue: String, disabled: Boolean })
defineEmits(['update:modelValue'])
</script>
<template>
  <div class="mode-select" role="radiogroup" aria-label="选择功能">
    <div class="mode-card" :class="{ active: modelValue === '1' || modelValue === '2' || modelValue === '5' }">
      <button class="mode-tile" type="button" :disabled="disabled" @click="$emit('update:modelValue', ['2', '5'].includes(modelValue) ? modelValue : '1')"><span class="tile-head"><span class="tile-title">收款组</span><span class="tile-check" :class="{ on: modelValue === '1' || modelValue === '2' || modelValue === '5' }">✓</span></span><span class="tile-sub">发票识别与信息转 Excel</span><span class="tile-desc">按人员选择处理方式，支持图片表格、含图片信息表格及纯识别表格。</span></button>
      <div v-if="modelValue === '1' || modelValue === '2' || modelValue === '5'" class="submode-picker"><span class="submode-label">选择收款组人员</span><div class="submode-options"><button type="button" class="submode-btn" :class="{ on: modelValue === '1' }" :disabled="disabled" @click="$emit('update:modelValue', '1')">谢莉丽</button><button type="button" class="submode-btn" :class="{ on: modelValue === '2' }" :disabled="disabled" @click="$emit('update:modelValue', '2')">赵淑华</button><button type="button" class="submode-btn" :class="{ on: modelValue === '5' }" :disabled="disabled" @click="$emit('update:modelValue', '5')">邵梅琳</button></div></div>
    </div>
    <button class="mode-tile standalone" :class="{ active: modelValue === '3' }" type="button" :disabled="disabled" @click="$emit('update:modelValue', '3')"><span class="tile-head"><span class="tile-title">付款组</span><span class="tile-check" :class="{ on: modelValue === '3' }">✓</span></span><span class="tile-sub">发票明细识别转 Excel</span><span class="tile-desc">识别英文发票的 INVOICE / 明细行，支持现有十三种发票版式。</span></button>
    <button class="mode-tile standalone" :class="{ active: modelValue === '4' }" type="button" :disabled="disabled" @click="$emit('update:modelValue', '4')"><span class="tile-head"><span class="tile-title">报表组</span><span class="tile-check" :class="{ on: modelValue === '4' }">✓</span></span><span class="tile-sub">表格处理</span><span class="tile-desc">上传 Excel 报表，按规则清洗、整理和生成结果。</span></button>
  </div>
</template>
<style scoped>
.mode-select{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.mode-card,.mode-tile.standalone{background:var(--surface);border:1.5px solid var(--border);border-radius:var(--radius);overflow:hidden}.mode-card.active,.mode-tile.standalone.active{border-color:var(--primary);background:var(--primary-soft);box-shadow:var(--shadow-sm)}.mode-tile{width:100%;display:flex;flex-direction:column;gap:6px;align-items:stretch;text-align:left;padding:20px;background:transparent;border:0;cursor:pointer}.mode-tile:hover:not(:disabled){background:color-mix(in srgb,var(--primary-soft) 45%,transparent)}.mode-tile:focus-visible,.submode-btn:focus-visible{outline:2px solid var(--primary);outline-offset:-2px}.mode-tile:disabled,.submode-btn:disabled{opacity:.6;cursor:not-allowed}.tile-head{display:flex;justify-content:space-between;align-items:center}.tile-title{font-size:17px;font-weight:800}.tile-check{width:22px;height:22px;border-radius:50%;border:1.5px solid var(--border-strong);display:grid;place-items:center;color:transparent}.tile-check.on{background:var(--primary);border-color:var(--primary);color:#fff}.tile-sub{font-size:13px;font-weight:600;color:var(--text)}.tile-desc{font-size:12.5px;color:var(--text-soft);line-height:1.6}.submode-picker{display:flex;flex-direction:column;gap:8px;padding:12px 20px 16px;border-top:1px dashed var(--border-strong)}.submode-label{font-size:12px;font-weight:700;color:var(--text-soft)}.submode-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.submode-btn{min-height:40px;padding:6px 10px;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--text-soft);text-align:center;font-size:12px;cursor:pointer}.submode-btn.on{border-color:var(--primary);color:var(--primary-ink);font-weight:700;box-shadow:inset 0 -3px 0 var(--primary)}@media (max-width:640px){.mode-select{grid-template-columns:1fr}}@media (max-width:520px){.submode-options{grid-template-columns:1fr}}
</style>
